onlyBuiltDependencies:
  - ' '
  - /
  - '@'
  - a
  - b
  - c
  - d
  - e
  - esbuild
  - g
  - i
  - l
  - m
  - msw
  - n
  - o
  - p
  - r
  - s
  - sharp
  - t
  - u
  - unrs-resolver
  - w
  - x
